// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.2
// source: api/proto/info.proto

package info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileServerInfo the file server basic info
type FileServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ServerAddr the server running address
	ServerAddr string `protobuf:"bytes,1,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	// SourcePath the source base path of the file server
	SourcePath string `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	// DestPath the dest base path of the file server
	DestPath string `protobuf:"bytes,3,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	// QueryAddr the query api address of the file server
	QueryAddr string `protobuf:"bytes,4,opt,name=query_addr,json=queryAddr,proto3" json:"query_addr,omitempty"`
	// PushAddr the push api address of the file server
	PushAddr string `protobuf:"bytes,5,opt,name=push_addr,json=pushAddr,proto3" json:"push_addr,omitempty"`
}

func (x *FileServerInfo) Reset() {
	*x = FileServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileServerInfo) ProtoMessage() {}

func (x *FileServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileServerInfo.ProtoReflect.Descriptor instead.
func (*FileServerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_info_proto_rawDescGZIP(), []int{0}
}

func (x *FileServerInfo) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *FileServerInfo) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *FileServerInfo) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *FileServerInfo) GetQueryAddr() string {
	if x != nil {
		return x.QueryAddr
	}
	return ""
}

func (x *FileServerInfo) GetPushAddr() string {
	if x != nil {
		return x.PushAddr
	}
	return ""
}

var File_api_proto_info_proto protoreflect.FileDescriptor

var file_api_proto_info_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0e, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75,
	0x73, 0x68, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x75, 0x73, 0x68, 0x41, 0x64, 0x64, 0x72, 0x32, 0x48, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x6f, 0x2d, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x6f, 0x66, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_info_proto_rawDescOnce sync.Once
	file_api_proto_info_proto_rawDescData = file_api_proto_info_proto_rawDesc
)

func file_api_proto_info_proto_rawDescGZIP() []byte {
	file_api_proto_info_proto_rawDescOnce.Do(func() {
		file_api_proto_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_info_proto_rawDescData)
	})
	return file_api_proto_info_proto_rawDescData
}

var file_api_proto_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_info_proto_goTypes = []interface{}{
	(*FileServerInfo)(nil), // 0: info.FileServerInfo
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_api_proto_info_proto_depIdxs = []int32{
	1, // 0: info.InfoService.GetInfo:input_type -> google.protobuf.Empty
	0, // 1: info.InfoService.GetInfo:output_type -> info.FileServerInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_info_proto_init() }
func file_api_proto_info_proto_init() {
	if File_api_proto_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_info_proto_goTypes,
		DependencyIndexes: file_api_proto_info_proto_depIdxs,
		MessageInfos:      file_api_proto_info_proto_msgTypes,
	}.Build()
	File_api_proto_info_proto = out.File
	file_api_proto_info_proto_rawDesc = nil
	file_api_proto_info_proto_goTypes = nil
	file_api_proto_info_proto_depIdxs = nil
}
