# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        go: [ '1.19','1.20' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic -timeout=10m

      - name: Test Encrypt
        run: go test -v -race -tags=encrypt_test ./encrypt

      - name: Test HttpUtil
        run: go test -v -race -tags=httputil_test ./util/httputil

      - name: Test Tran
        run: go test -v -race -tags=tran_test ./tran

      - name: Test Integration
        run: go test -v -race -tags=integration_test ./integration

      - name: Codecov
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest'